[[Aravis]]
arch = "aarch64"
git-tree-sha1 = "e83eccb57fa9bfc035ac9295f54d54f7becb27ba"
os = "macos"

    [[Aravis.download]]
    sha256 = "ad372ee403158b0d03c7d41496faa2446e365c0d03b02459aa333a9dcfb0afa0"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.aarch64-apple-darwin.tar.gz"
[[Aravis]]
arch = "aarch64"
git-tree-sha1 = "6b32f075ff886bd7c713ce9cd65c1438ee987e78"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "659e2ea4123f302d7b788de63a01351607a09918e162fdb3c424876c50e0c99b"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.aarch64-linux-gnu.tar.gz"
[[Aravis]]
arch = "aarch64"
git-tree-sha1 = "a64a3e636960937f5828e258c40d97146431d8f1"
libc = "musl"
os = "linux"

    [[Aravis.download]]
    sha256 = "9fd12f26cd6d9517c28b475f78a50eba57f22146b9b4521848fe16e8cec94d38"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.aarch64-linux-musl.tar.gz"
[[Aravis]]
arch = "aarch64"
git-tree-sha1 = "b556bc028cd535ed91dc56f5da89316145eb0581"
os = "freebsd"

    [[Aravis.download]]
    sha256 = "6262936ad47a78d2f57ad6b425cf08505c5967981445cfc40ef75ef4f9241e28"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.aarch64-unknown-freebsd.tar.gz"
[[Aravis]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c5d972d11c0e0ba9c852d8f7b19d3cd4266ee32"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "25b6ca36a6cf55d7908eb6efa78626296fe31eae7c01fe7d05e1e5dd2759f71b"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.armv6l-linux-gnueabihf.tar.gz"
[[Aravis]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16c71cd10ba168587172e567f3b8ba706c9da913"
libc = "musl"
os = "linux"

    [[Aravis.download]]
    sha256 = "ddf5e394ed4ce821fddb3268d60fdc92289531f2af057fb97a0091186a939983"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.armv6l-linux-musleabihf.tar.gz"
[[Aravis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b7f897fc7a0a6fccafba72a60fabf047882e15f3"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "53b8f25e22f749a12709bbaf22348a494829574e94e89431f71c6501c04fbc3f"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.armv7l-linux-gnueabihf.tar.gz"
[[Aravis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1fad4991c6671b89b4299fc5a21c5987c01eebf"
libc = "musl"
os = "linux"

    [[Aravis.download]]
    sha256 = "331ec6dc66fe23ccf9af2ccb7822dbd7b2f099c533295cf091fc9e679da1c111"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.armv7l-linux-musleabihf.tar.gz"
[[Aravis]]
arch = "i686"
git-tree-sha1 = "ddea9b55b12d11d4f6ad60a18b1324bb6fcf43d3"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "ac3000add787dcc99ae30850cabe34912be6a9754adec29da887f0694563baac"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.i686-linux-gnu.tar.gz"
[[Aravis]]
arch = "i686"
git-tree-sha1 = "154084dbec6f61c75e57cc6be11d359c8be5fb43"
libc = "musl"
os = "linux"

    [[Aravis.download]]
    sha256 = "98463a40aba7f1d33231b8155aba02393509f387bbc8d2263f0b408a5097bfd8"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.i686-linux-musl.tar.gz"
[[Aravis]]
arch = "i686"
git-tree-sha1 = "5199ff73375cfc21a99dae7beebd93fb0ec4649e"
os = "windows"

    [[Aravis.download]]
    sha256 = "44c52553707ecc28ed2f37d0ad4ae508a23660ac07fe634eb63d9d18f338cee5"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.i686-w64-mingw32.tar.gz"
[[Aravis]]
arch = "powerpc64le"
git-tree-sha1 = "249ca929d36f716cc4b78c0708067924bc2bfa24"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "4f69fdf8863c86487e7efbd531b72d0671ff712925d51498314b8dff64310d56"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.powerpc64le-linux-gnu.tar.gz"
[[Aravis]]
arch = "x86_64"
git-tree-sha1 = "1b4d1fa2ebbfd2c33224cdb091c843cc5e8f19e6"
os = "macos"

    [[Aravis.download]]
    sha256 = "b632b0aef1af16b12180773f9fa150da7030853077a9627e7499105f89344417"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.x86_64-apple-darwin.tar.gz"
[[Aravis]]
arch = "x86_64"
git-tree-sha1 = "71140d10d1e0f4db2048039e7b84f3ef0083d93c"
libc = "glibc"
os = "linux"

    [[Aravis.download]]
    sha256 = "9105d17a733d5f8a03bdf00741524e3d6a2610dfeabbc3cabad4635ded3e9bac"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.x86_64-linux-gnu.tar.gz"
[[Aravis]]
arch = "x86_64"
git-tree-sha1 = "d79fa8596694208bf0e9a9d86955028a9e3d1a82"
libc = "musl"
os = "linux"

    [[Aravis.download]]
    sha256 = "f06228e27ab15c2e288629ebd67fa568696139685bfae0ee2bf4d82de90fdb23"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.x86_64-linux-musl.tar.gz"
[[Aravis]]
arch = "x86_64"
git-tree-sha1 = "1abb6ba317fe223438bb80d8f15da8e5658f776e"
os = "freebsd"

    [[Aravis.download]]
    sha256 = "39952197b1e30139d2af9c258ceaaaef066ca8a7e8f75237ae431cdfe1fcd794"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.x86_64-unknown-freebsd.tar.gz"
[[Aravis]]
arch = "x86_64"
git-tree-sha1 = "611a56b29acc2786b22bcf23a3198083ad36bc40"
os = "windows"

    [[Aravis.download]]
    sha256 = "150f1ef1993ad33de50445f093e850086cb8d91d3c8766e358977f03e0736e38"
    url = "https://github.com/JuliaBinaryWrappers/Aravis_jll.jl/releases/download/Aravis-v0.8.33+0/Aravis.v0.8.33.x86_64-w64-mingw32.tar.gz"
