# Autogenerated wrapper script for Aravis_jll for aarch64-linux-musl
export arv_tool, libaravis

using Glib_jll
using libusb_jll
using XML2_jll
JLLWrappers.@generate_wrapper_header("Aravis")
JLLWrappers.@declare_library_product(libaravis, "libaravis-0.8.so.0")
JLLWrappers.@declare_executable_product(arv_tool)
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll, libusb_jll, XML2_jll)
    JLLWrappers.@init_library_product(
        libaravis,
        "lib/libaravis-0.8.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        arv_tool,
        "bin/arv-tool-0.8",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
